### ISSUE TITLE
Whittier Yard Adjustments

### ISSUE THREAD

**Issue by dazzlepony** [AlinaNova21/Railroader-Mods#20]
Some in-world assets and textures were added or changed with the most recent game update and the new telephone/telegraph lines clip through trains passing along the Whittier Sawmill connection.  I haven't completed the yard yet so don't know how they interact with it but at minimum the poles might need to just be taller or raised?

**Comment by AlinaNova21** [comment]
This was fixed in one of the recent builds by shifting the yard over a bit and raising the poles as well.
