### ISSUE TITLE
Alarka City Turnaround

### ISSUE THREAD

**Issue by dazzlepony** [AlinaNova21/Railroader-Mods#4]
A loop of some sorts enabling longer passenger trains (3+ coaches) to be turned around without shuffling them through the wye.  Alternately, extend the stub of the Wye to fit a longer train so it can be turned that way.

![image](https://github.com/AlinaNova21/Railroader-Mods/assets/163030671/eed21809-2a85-4f59-995f-370ff98f82e2)
_(yellow line showing extension of wye stub in Alarka City)_

**Comment by AlinaNova21** [comment]
Added in v1.3.24078.548 :)
